trigger:
- main

pool:
  name: Docker-Test

steps:
- checkout: self

- script: |
    echo "=========================================="
    echo "CONTENIDO DESCARGADO DESDE AZURE REPOS"
    echo "=========================================="

    echo "Build Sources Directory:"
    echo "$(Build.SourcesDirectory)"

    echo ""
    echo "Contenido:"
    ls -la "$(Build.SourcesDirectory)/agente_ia_backend"

- script: |
    sudo /usr/local/sbin/deploy-agente-ia.sh "$(Build.SourcesDirectory)/agente_ia_backend"
  displayName: "Deploy Agente IA TEST"