trigger:
- main

stages:

# ==========================================
# VALIDACION PREVIA
# ==========================================
- stage: Validate
  displayName: "Validar Código"

  jobs:
  - job: DockerValidation

    pool:
      name: Docker-Test

    steps:

    - checkout: self

    - script: |
        echo "=========================================="
        echo "CONTENIDO DESCARGADO DESDE AZURE REPOS"
        echo "=========================================="

        echo "Build Sources Directory:"
        echo "$(Build.SourcesDirectory)"

        echo ""
        echo "Contenido:"
        ls -la "$(Build.SourcesDirectory)/agente_ia_backend"

      displayName: "Validar Checkout"

    - script: |
        set -e

        cd "$(Build.SourcesDirectory)/agente_ia_backend"

        echo "=========================================="
        echo "VALIDACION PREVIA DEL DOCKER BUILD"
        echo "=========================================="

        docker build \
          -t agente-ia-validation:$(Build.BuildId) \
          .

        echo "Docker Build OK"

      displayName: "Validar Docker Build"


# ==========================================
# DEPLOY DEV
# ==========================================
- stage: Deploy_Dev
  displayName: "Deploy DEV"

  dependsOn: Validate

  condition: succeeded()

  jobs:
  - deployment: DeployAgenteIA

    pool:
      name: Docker-Test

    environment: Dev

    strategy:
      runOnce:
        deploy:

          steps:

          - checkout: self

          - script: |
              echo "=========================================="
              echo "RELEASE INFORMATION"
              echo "=========================================="

              echo "Build ID........: $(Build.BuildId)"
              echo "Commit..........: $(Build.SourceVersion)"
              echo "Branch..........: $(Build.SourceBranchName)"
              echo "Sources.........: $(Build.SourcesDirectory)"

            displayName: "Release Info"

          - script: |
              sudo BUILD_BUILDID=$(Build.BuildId) \
              /usr/local/sbin/deploy-agente-ia.sh \
              "$(Build.SourcesDirectory)/agente_ia_backend"

            displayName: "Deploy Agente IA DEV"