trigger:
- main

stages:

- stage: Deploy_Test
  displayName: "Deploy TEST"

  jobs:

  - deployment: DeployAgenteIA

    pool:
      name: Docker-Test

    environment: Testing

    strategy:
      runOnce:

        deploy:

          steps:

          - checkout: self

          - script: |
              echo "=========================================="
              echo "RELEASE INFORMATION"
              echo "=========================================="

              echo "Build ID : $(Build.BuildId)"
              echo "Commit   : $(Build.SourceVersion)"
              echo "Branch   : $(Build.SourceBranchName)"
              echo "Source   : $(Build.SourcesDirectory)"

            displayName: "Release Info"

          - script: |
              sudo /usr/local/sbin/deploy-agente-ia.sh \
              "$(Build.SourcesDirectory)/agente_ia_backend" \
              "$(Build.BuildId)"

            displayName: "Deploy Agente IA TEST"


- stage: Deploy_Prod_Artigas

  displayName: "Deploy PROD Artigas"

  dependsOn: Deploy_Test

  condition: succeeded()

  jobs:

  - deployment: DeployAgenteIAProd

    pool:
      name: Docker Artigas

    environment: Produccion-Artigas

    strategy:
      runOnce:

        deploy:

          steps:

          - checkout: self

          - script: |
              echo "=========================================="
              echo "PRODUCTION RELEASE INFORMATION"
              echo "=========================================="

              echo "Build ID : $(Build.BuildId)"
              echo "Commit   : $(Build.SourceVersion)"
              echo "Branch   : $(Build.SourceBranchName)"
              echo "Source   : $(Build.SourcesDirectory)"

            displayName: "Release Info PROD"

          - script: |
              sudo /usr/local/sbin/deploy-agente-ia.sh \
              "$(Build.SourcesDirectory)/agente_ia_backend" \
              "$(Build.BuildId)"

            displayName: "Deploy Agente IA PROD Artigas"


- stage: Deploy_Prod_SanLorenzo

  displayName: "Deploy PROD San Lorenzo"

  dependsOn: Deploy_Prod_Artigas

  condition: succeeded()

  jobs:

  - deployment: DeployAgenteIAProdSL

    pool:
      name: Docker San Lorenzo

    environment: Produccion-SanLorenzo

    strategy:
      runOnce:

        deploy:

          steps:

          - checkout: self

          - script: |
              echo "=========================================="
              echo "PRODUCTION RELEASE INFORMATION"
              echo "=========================================="

              echo "Build ID : $(Build.BuildId)"
              echo "Commit   : $(Build.SourceVersion)"
              echo "Branch   : $(Build.SourceBranchName)"
              echo "Source   : $(Build.SourcesDirectory)"

            displayName: "Release Info PROD San Lorenzo"

          - script: |
              sudo /usr/local/sbin/deploy-agente-ia.sh \
              "$(Build.SourcesDirectory)/agente_ia_backend" \
              "$(Build.BuildId)"

            displayName: "Deploy Agente IA PROD San Lorenzo"