trigger: none

stages:

- stage: Rollback_Test
  displayName: "Rollback TEST"

  jobs:

  - deployment: RollbackAgenteIA

    pool:
      name: Docker-Test

    environment: Testing

    strategy:
      runOnce:

        deploy:

          steps:

          - script: |
              sudo /usr/local/sbin/rollback-agente-ia.sh

            displayName: "Rollback Agente IA TEST"