trigger: none

stages:

- stage: Rollback_Prod_Artigas

  displayName: "Rollback PROD Artigas"

  jobs:

  - deployment: RollbackAgenteIA

    pool:
      name: Docker Artigas

    environment: Produccion-Artigas

    strategy:
      runOnce:

        deploy:

          steps:

          - script: |
              sudo /usr/local/sbin/rollback-agente-ia.sh

            displayName: "Rollback Agente IA PROD Artigas"